---
title: "BLM_Colorado_Data_Variables"
format: html
editor: visual
---

## Dataset

```{r}
library(tidyverse)
library(rvest)
library(polite)
library(tidyverse)
library(stringr)
library(stringi)
```

```{r}
blm_colorado <- read.csv("blm_colorado.csv")
```

## Cleaning
```{r}
blm_colorado_2 <- blm_colorado |>
  mutate(address = str_c(Address_1, Address_2, sep = " "),
         )|>
  select(-X)|>
  group_by(Phone_Number)|>
  mutate(ContactRegion = cur_group_id())|>
  ungroup()

listed_activities <- c("CAMPING","WATER SPORTS","ENVIRONMENTAL EDUCATION","NON-MOTORIZED BOATING","DAY USE AREA", "PADDLE BOATING","WATER ACCESS","RAFTING","WHITEWATER RAFTING","BIRDING", "BACKPACKING","INTERPRETIVE PROGRAMS","WILDLIFE VIEWING","FISHING", "BOATING", "HORSEBACK RIDING","")

# Column with binary for each word, DIDN'T WORK?
for (word in listed_activities) {
  blm_colorado_2 <- blm_colorado_2 |>
    mutate(!!word := as.integer(str_detect(blm_colorado_2$Activities, word)))
}

blm_colorado_2|>
  filter(is.na(Activities))

```
#Var. 1 Binary of Each Activity

```{r}
blm_colorado_2
```
Already exists?

#Var. 2 Sum of Activities Offered

```{r}
blm_colorado_2 |>
  sum(`CAMPING`, `WATER SPORTS`, `ENVIRONMENTAL EDUCATION`, `NON-MOTORIZED BOATING`, `DAY USE AREA`, `PADDLE BOATING`, `WATER ACCESS`, RAFTING, `WHITEWATER RAFTING`, BIRDING, BACKPACKING, `INTERPRETIVE PROGRAMS`, `WILDLIFE VIEWING`, FISHING, BOATING, `HORSEBACK RIDING`)
```


#Var. 3 Type of Attraction



#Var. 4 ID for sites w/ shared phone/address



#Var. 5 Str_length of Descriptions

```{r}
blm_colorado_2$Description_Length = str_length(blm_colorado_2$Description)

blm_colorado_2$Description_Length_Words = stri_count_words(blm_colorado_2$Description)

blm_colorado_2
```


#Var. 6 Str_length of Directions

```{r}
blm_colorado_2$Direction_Length = str_length(blm_colorado_2$Directions)

blm_colorado_2

blm_colorado_2$Direction_Length_Words = stri_count_words(blm_colorado_2$Directions)
```

