---
title: "BLM_Colorado_Data_Cleaning"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(rvest)
library(polite)
library(tidyverse)
library(stringr)
library(maps)
library(mapview)
library(tmap)
```

## Code

```{r}
blm_colorado <- read.csv("~/samuelson-hickman_test/blm_colorado.csv")
```

## Remove Unneeded Columns and Add Activities Columns

```{r}
blm_colorado_2 <- blm_colorado |>
  mutate(address = str_c(Address_1, Address_2, sep = " "),
         )|>
  select(-X)|>
  group_by(Phone_Number)|>
  mutate(ContactRegion = cur_group_id(),
         Description = str_replace(Description, "^Overview",""))|>
  ungroup()|>
  mutate(desc_length = str_count(Description))

listed_activities <- c("CAMPING","WATER SPORTS","ENVIRONMENTAL EDUCATION","NON-MOTORIZED BOATING","DAY USE AREA", "PADDLE BOATING","WATER ACCESS","RAFTING","WHITEWATER RAFTING","BIRDING", "BACKPACKING","INTERPRETIVE PROGRAMS","WILDLIFE VIEWING","FISHING", "BOATING", "HORSEBACK RIDING","")

# Column with binary for each word
for (word in listed_activities) {
  blm_colorado_2 <- blm_colorado_2 |>
    mutate(!!word := as.numeric(str_detect(blm_colorado_2$Activities, word)))
}

blm_colorado_2|>
  filter(is.na(Activities)
# Four sites shown

blm_colorado_2<-blm_colorado_2|>
  mutate(act_count = count("CAMPING", "BACKPACKING")

```
