---
title: "Test Flexdash"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: inline
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse) 
library(knitr)
library(ggplot2)
library(shiny)
library(dplyr)
library(sp)
library(sf)
library(leaflet)
library(mapview)
```

```{r}
#| message: false
#| warning: false
#| include: false

BLM <- read_csv("blm_colorado_3.csv")

BLM <- BLM %>%
  rename(Address1 = `Address_1`,
         Address2 = `Address_2`,
         ZipCode = `Zip_Code`,
         PhoneNumber = `Phone_Number`,
         PICKNICKING = `PICNICkING`,
         DescriptionCharacterLength = `Description_Length`,
         DescriptionLengthWords = `Description_Length_Words`,
         DirectionCharacterLength = `Direction_Length`,
         DirectionLengthWords = `Direction_Length_Words`)

print(BLM)
BLM
```
About The Project
=======================================================================

Row
-----------------------------------------------------------------------
**What Are we Investigating?**

Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Our Key Questions

why?

### Data Attribution

When?

Visualizations
=======================================================================

ROW {.tabset .tabset-fade}
-----------------------------------------------------------------------


### Total Presence of activity

```{r}

ui <- fluidPage(
titlePanel("BLM Histogram Viewer"),
 sidebarLayout(
  sidebarPanel(
      
    selectInput(
      inputId = "xvar",
      label = "Choose a variable:",
      choices = c("CAMPING", "WATER SPORTS", "ENVIRONMENTAL EDUCATION", "NON-MOTORIZED BOATING", "DAY USE AREA", "PADDLE BOATING", "WATER ACCESS", "RAFTING", "WHITEWATER RAFTING", "BIRDING", "BACKPACKING", "INTERPRETIVE PROGRAMS", "WILDLIFE VIEWING", "FISHING", "BOATING", "HORSEBACK RIDING", "HIKING", "OFF HIGHWAY VEHICLE", "RECREATIONAL VEHICLES", "SENIC DRIVE", "PHOTOGRAPHY", "CLIMBING", "HUNTING", "WILDERNESS", "INFORMATION SITE", "PICNICKING"),
      selected = "CAMPING")),
   mainPanel(
    plotOutput("histPlot"))))



server <- function(input, output) {
output$histPlot <- renderPlot({
  ggplot(BLM, aes(x = .data[[input$xvar]])) +
    geom_bar(
        bins = 20,
        fill = "steelblue",
        color = "black") +
      labs(
        title = paste("Histogram of", input$xvar),
        x = input$xvar,
        y = "Count") +
      theme_minimal()})}

shinyApp(ui = ui, server = server)
#"CAMPING", "WATER SPORTS", "ENVIRONMENTAL EDUCATION", "NON-MOTORIZED BOATING", "DAY USE AREA", "PADDLE BOATING", "WATER ACCESS", "RAFTING", "WHITEWATER RAFTING", "BIRDING", "BACKPACKING", "INTERPRETIVE PROGRAMS", "WILDLIFE VIEWING", "FISHING", "BOATING", "HORSEBACK RIDING", "HIKING", "OFF HIGHWAY VEHICLE", "RECREATIONAL VEHICLES", "SENIC DRIVE", "PHOTOGRAPHY", "CLIMBING", "HUNTING", "WILDERNESS", "INFORMATION SITE", "PICNICKING"     
```


### Total Presence of Each Activity
```{r}

ui <- fluidPage(
titlePanel("BLM Recreation Activity Counts"),
mainPanel(
  plotOutput("barPlot", height = "700px")))

server <- function(input, output) {
output$barPlot <- renderPlot({
    
activities <- c(
      "CAMPING", "WATER SPORTS", "ENVIRONMENTAL EDUCATION", "NON-MOTORIZED BOATING", "DAY USE AREA", "PADDLE BOATING", "WATER ACCESS", "RAFTING", "WHITEWATER RAFTING", "BIRDING", "BACKPACKING", "INTERPRETIVE PROGRAMS", "WILDLIFE VIEWING", "FISHING", "BOATING", "HORSEBACK RIDING", "HIKING", "OFF HIGHWAY VEHICLE", "RECREATIONAL VEHICLES", "SENIC DRIVE", "PHOTOGRAPHY", "CLIMBING", "HUNTING", "WILDERNESS", "INFORMATION SITE", "PICNICKING")
    
activity_counts <- data.frame(
  Activity = activities,
  Count = sapply(activities, function(x) {
    sum(BLM[[x]] == 1, na.rm = TRUE)
      }))

activity_counts <- activity_counts %>%
  arrange(desc(Count))
    
ggplot(activity_counts,
  aes(x = reorder(Activity, Count), y = Count)) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(
    title = "Total Number of Recreation Sites by Activity",
    x = "Activity",
    y = "Total Instances of Activity") +
  theme_minimal(base_size = 14)})}

shinyApp(ui = ui, server = server)
```

### Length of Site Descirption

```{r}
ui <- fluidPage(
titlePanel("BLM Histogram Viewer"),
 sidebarLayout(
  sidebarPanel(
      
  selectInput(
    inputId = "xvar",
    label = "Choose a variable:",
    choices = c("DescriptionLengthWords", "DescriptionCharacterLength"),
    selected = "DescriptionLengthWords")),
   mainPanel(
    plotOutput("histPlot"))))


server <- function(input, output) {
output$histPlot <- renderPlot({
  ggplot(BLM, aes(x = .data[[input$xvar]])) +
    geom_histogram(
        bins = 20,
        fill = "steelblue",
        color = "black") +
      labs(
        title = paste("Histogram of", input$xvar),
        x = input$xvar,
        y = "Count") +
      theme_minimal()})}

shinyApp(ui = ui, server = server)
```

### Overivew of Activity Locations

```{r}
df <- BLM |>
  filter(Latitude != 0)

# Create point dataframe
points_df <- data.frame(
  lng = df$Longitude,
  lat = df$Latitude,
  names = df$BLM_Name)

# Convert the data frame to a spatial points data frame
points_sdf <- st_as_sf(
  points_df,
  coords = c("lng", "lat"),
  crs = 4326)

# Plot the points on a map
mapview(points_sdf, label = points_sdf$names, col.regions = "darkgreen", legend = FALSE)

```

### Activity Density Per Location

```{r}
library(sf)
library(mapview)
library(dplyr)

df <- BLM |>
  filter(Latitude != 0)

# Create point dataframe
points_df <- data.frame(
  lng = df$Longitude,
  lat = df$Latitude,
  names = df$BLM_Name)

# Convert the data frame to a spatial points data frame
points_sdf <- st_as_sf(
  points_df,
  coords = c("lng", "lat"),
  crs = 4326)

# Plot the points on a map
mapview(points_sdf, label = points_sdf$names, col.regions = "darkgreen", legend = FALSE)


```

#Density attempt 2

```{r}
library(sf)
library(mapview)
library(dplyr)

activity_cols <- c(
"CAMPING", "WATER SPORTS", "ENVIRONMENTAL EDUCATION", "NON-MOTORIZED BOATING", "DAY USE AREA", "PADDLE BOATING", "WATER ACCESS", "RAFTING", "WHITEWATER RAFTING", "BIRDING", "BACKPACKING", "INTERPRETIVE PROGRAMS", "WILDLIFE VIEWING", "FISHING", "BOATING", "HORSEBACK RIDING", "HIKING", "OFF HIGHWAY VEHICLE", "RECREATIONAL VEHICLES", "SENIC DRIVE", "PHOTOGRAPHY", "CLIMBING", "HUNTING", "WILDERNESS", "INFORMATION SITE", "PICNICKING")

df <- BLM |>
  filter(Latitude != 0) |>
  mutate(
    activity_count = rowSums(
      across(all_of(activity_cols)) == 1,
      na.rm = TRUE))

points_sdf <- st_as_sf(
  df,
  coords = c("Longitude", "Latitude"),
  crs = 4326)

mapview(
  points_sdf,
  zcol = "activity_count",
  cex = "activity_count",
  col.regions = colorRampPalette(c("lightblue", "orange", "red")),
  legend = TRUE,
  label = points_sdf$BLM_Name)
```

